site_name: argument_topic_diversity
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: argument_topic_diversity
      handlers:
        python:
          options:
            docstring_style: numpy